### ISSUE TITLE
I forked the lab into the learnIDE

### ISSUE THREAD

**Issue by nadukrow** [learn-co-curriculum/intro-to-capybara#14] opened 2016-09-30 14:29 UTC
Forked the lab into the learnIDE and finished it yet it still shows that I haven't forked it. I'll be moving on but I just wanted to raise the issue.

**Comment by aturkewi** [comment] 2016-11-28 17:54
Hey @nadukrow I'm going to close this issue here because it's not really a problem with the lab, but just with your specific fork. 

This can usually be fixed by going onto github and _deleting_ your fork of the lab and then re-forking it. The problem is that when the fork event happened, the message somehow got lost.

If you try this and you're still having an issues, the best place to get help would be the Ask A Question button!

**Closed as completed by aturkewi** 2016-11-28 17:54 UTC
Labels: Product
